/* ============================================================
 * data.js — 총기 / 탄약 / 임무 데이터
 *
 * 설명(desc)은 제조사 공식 페이지의 소개문을 한국어로 옮긴 것이며,
 * 공식 페이지에 내용이 없는 항목(M33 Ball)만 위키피디아를 참조했다.
 * descSource: 'official' | 'wikipedia', descSourceUrl: 원문 링크.
 * BC/총구속도는 제조사 공표값 기준 (m/s 환산).
 * ============================================================ */
'use strict';

const GameData = {

  rifles: [
    {
      id: 'rem700',
      name: 'Remington 700',
      caliber: '.308 Winchester',
      ammoIds: ['gmm308_168', 'gmm308_175'],
      weightKg: 3.4,
      barrelMm: 508,
      magCapacity: 4,
      effectiveRangeM: 800,
      swayFactor: 1.05,
      recoilMrad: 2.2,
      desc: '1962년 출시 이후 가장 많이 판매된 볼트액션 소총 — "역대 1위 볼트액션"으로 불린다. 군·법집행기관 저격수의 표준 플랫폼으로 채택되어 왔으며, 별도 손질 없이도(out-of-the-box) 뛰어난 정확도로 명성이 높다. 현행 생산분에는 Timney 트리거가 기본 장착된다. (SPS Tactical .308: 20인치 헤비 총열, 1:10 트위스트)',
      descSource: 'official',
      descSourceUrl: 'https://www.remarms.com/rifles/bolt-action/model-700/',
    },
    {
      id: 'trg42',
      name: 'Sako TRG 42',
      caliber: '.338 Lapua Magnum',
      ammoIds: ['scenar250', 'scenar300'],
      weightKg: 5.1,
      barrelMm: 690,
      magCapacity: 5,
      effectiveRangeM: 1500,
      swayFactor: 0.85,
      recoilMrad: 2.8,
      desc: '전 세계 경기 사수들이 "가장 정확하고 신뢰성 있는 소총 중 하나"로 인정하는 TRG 시리즈의 .338 라푸아 매그넘 모델. 장거리·초장거리의 까다로운 사격 상황에 적응하도록 설계됐다. 알루미늄 보강 복합소재 스톡은 높이·치크피스·버트플레이트 조절이 가능하고, 액션 프레임은 특수 합금강 냉간 단조로 강성을 높였다.',
      descSource: 'official',
      descSourceUrl: 'https://www.sako.fi/en-us/rifles/sako-trg/trg-42',
    },
    {
      id: 'axsr',
      name: 'Accuracy International AXSR',
      caliber: '.338 Lapua Magnum',
      ammoIds: ['scenar250', 'scenar300'],
      weightKg: 7.39,
      barrelMm: 686,
      magCapacity: 10,
      effectiveRangeM: 1500,
      swayFactor: 0.75,
      recoilMrad: 2.4,
      desc: '고성능 롱액션 멀티캘리버 저격총 시스템. 6.5 CM / .308 Win / .300 WM / .338 LM 4개 구경으로 출고되며 총열·노리쇠·탄창 킷 교환만으로 수 분 만에 구경 전환이 가능하다. AI가 영국에서 컷라이플링 방식으로 직접 제작한 총열과 중심 균형 설계가 직선적인 반동을 구현한다. 호주 국방군(ADF)의 차기 저격총으로 선정됐다.',
      descSource: 'official',
      descSourceUrl: 'https://www.accuracyinternational.com/axsr-mil',
    },
    {
      id: 'm107a1',
      name: 'Barrett M107A1',
      caliber: '.50 BMG',
      ammoIds: ['amax750', 'm33ball'],
      weightKg: 13.0,
      barrelMm: 737,
      magCapacity: 10,
      effectiveRangeM: 1800,
      swayFactor: 0.7,
      recoilMrad: 3.5,
      desc: '전작 대비 4파운드 경량화와 소음기 운용 최적화를 위해 모든 부품을 더 가볍고 강하게 재설계한 .50 BMG 반자동 소총. 초경질 PVD 코팅 마감, 티타늄 부품을 적용한 알루미늄 상부 리시버, 소음기 사용에 대응하는 개량형 노리쇠뭉치와 반동 시스템을 갖췄다. (29인치 총열, 1:15 트위스트, 10발 탄창)',
      descSource: 'official',
      descSourceUrl: 'https://barrett.net/products/firearms/m107a1/',
    },
    {
      id: 'm200',
      name: 'CheyTac M200 Intervention',
      caliber: '.408 CheyTac',
      ammoIds: ['ct419'],
      weightKg: 14.0,
      barrelMm: 749,
      magCapacity: 7,
      effectiveRangeM: 2500,
      swayFactor: 0.7,
      recoilMrad: 3.0,
      desc: 'CheyTac의 기함급 초장거리(ELR) 저격 플랫폼. 서브 MOA 정확도와 2,500 m 이상 교전 능력을 표방하며 .408/.375 CheyTac 총열 교환이 가능하다. CNC 가공 리시버, 40 MOA 스코프 레일, 조절식 트리거, 착탈식 머즐브레이크, 일체형 양각대, 7발 탄창, 모노포드 내장 조절식 개머리판이 표준 사양이다.',
      descSource: 'official',
      descSourceUrl: 'https://cheytac.com/precision-firearms/m200-intervention-sniper-rifle/',
    },
  ],

  ammo: [
    {
      id: 'gmm308_168',
      name: 'Federal Gold Medal Match 168gr SMK',
      caliber: '.308 Winchester',
      bulletGr: 168,
      diameterMm: 7.82,
      dragModel: 'G1',
      bc: 0.462,
      mv: 807.7,        // 2650 fps (24" 시험총열)
      mvSd: 3.0,
      sgFactor: 1.9,
      desc: '"어떤 소총탄보다 많은 경기에서 우승한" 정밀 제작 시에라 매치킹(SMK) 탄두에, 업계 최고 수준의 감도와 일관성을 내는 골드메달 전용 매치 프라이머를 결합했다. 보트테일 할로포인트 탄두가 일관된 장거리 정확도를 보장한다.',
      descSource: 'official',
      descSourceUrl: 'https://www.federalpremium.com/rifle/gold-medal/gold-medal-sierra-matchking/11-GM308M.html',
    },
    {
      id: 'gmm308_175',
      name: 'Federal Gold Medal Match 175gr SMK',
      caliber: '.308 Winchester',
      bulletGr: 175,
      diameterMm: 7.82,
      dragModel: 'G1',
      bc: 0.505,
      mv: 792.5,        // 2600 fps (24" 시험총열)
      mvSd: 3.0,
      sgFactor: 1.8,
      desc: '세계 정상급 사수들이 선택하는 시에라 매치킹 175gr 탄두를 골드메달 매치 프라이머, Federal 탄피, 전용 배합 장약과 결합한 매치 탄약. 보트테일 할로포인트 탄두가 매치 사수에게 필요한 탄도 성능의 여유를 제공하며 일관된 장거리 정확도를 보장한다.',
      descSource: 'official',
      descSourceUrl: 'https://www.federalpremium.com/rifle/gold-medal/gold-medal-sierra-matchking/11-GM308M2.html',
    },
    {
      id: 'scenar250',
      name: 'Lapua Scenar 250gr (GB488)',
      caliber: '.338 Lapua Magnum',
      bulletGr: 250,
      diameterMm: 8.58,
      dragModel: 'G1',
      bc: 0.648,
      mv: 915,
      mvSd: 3.5,
      sgFactor: 1.9,
      desc: '.338 라푸아 매그넘은 "극한의 장거리를 위해 만들어진 궁극의 센터파이어 소총탄"으로, 군용 명성과 함께 장거리 수렵·ELR 스포츠 사격에서 사용이 늘고 있다. 시나(Scenar)는 오픈팁 매치(OTM) 보트테일 탄두로, 국제 무대의 중·장거리 경기와 벤치레스트에서 탁월한 실적을 보유하고 있다.',
      descSource: 'official',
      descSourceUrl: 'https://www.lapua.com/product/338-lapua-mag-tactical-target-cartridge-scenar-162g-250gr-4318017/',
    },
    {
      id: 'scenar300',
      name: 'Lapua Scenar 300gr (GB528)',
      caliber: '.338 Lapua Magnum',
      bulletGr: 300,
      diameterMm: 8.58,
      dragModel: 'G1',
      bc: 0.736,
      mv: 837,
      mvSd: 3.5,
      sgFactor: 1.7,
      desc: '중량 19.4 g(300 gr) 시나 OTM 탄두를 장착한 라푸아의 전술/표적용 .338 라푸아 매그넘 탄약. 무거운 탄두와 높은 탄도계수(G1 0.736) 덕분에 극한 장거리에서 바람 편류에 강하고 잔존 에너지가 크다.',
      descSource: 'official',
      descSourceUrl: 'https://www.lapua.com/product/338-lapua-mag-tactical-target-cartridge-scenar-194g-300gr-4318013/',
    },
    {
      id: 'amax750',
      name: 'Hornady A-MAX Match 750gr',
      caliber: '.50 BMG',
      bulletGr: 750,
      diameterMm: 12.95,
      dragModel: 'G1',
      bc: 1.05,
      mv: 859.5,        // 2820 fps
      mvSd: 4.5,
      sgFactor: 1.8,
      desc: '공기역학적 시컨트 오자이브 형상, 날카로운 팁, 탁월한 동심도로 "비행의 완벽에 가까운" 극히 높은 탄도계수(G1 1.05)를 달성한 750gr A-MAX 탄두를 사용하는 매치급 .50 BMG 탄약. 표적·정밀 사격용 매치급 정확도를 제공한다.',
      descSource: 'official',
      descSourceUrl: 'https://www.hornady.com/ammunition/rifle/50-bmg-750-gr-a-max-match',
    },
    {
      id: 'm33ball',
      name: 'M33 Ball 661gr',
      caliber: '.50 BMG',
      bulletGr: 661,
      diameterMm: 12.95,
      dragModel: 'G1',
      bc: 0.62,         // 공식 BC 미공표 — 통용 근사값
      mv: 887,          // 2910 fps
      mvSd: 7.0,
      sgFactor: 1.8,
      desc: '미군 표준 .50 BMG 볼(Ball) 탄. 661gr FMJ 탄두이며 무도색 탄두 팁으로 식별된다(예광·소이·작약 없음). M2·M85 기관총용으로 대인·비장갑 표적을 상정해 만들어졌으며 .50 구경 소총에서도 널리 사용된다. 매치탄 대비 속도 편차가 커서 정밀 사격에는 불리하다.',
      descSource: 'wikipedia',
      descSourceUrl: 'https://en.wikipedia.org/wiki/.50_BMG',
    },
    {
      id: 'ct419',
      name: 'CheyTac 419gr Solid',
      caliber: '.408 CheyTac',
      bulletGr: 419,
      diameterMm: 10.36,
      dragModel: 'G1',
      bc: 0.949,
      mv: 838.8,        // 2752 fps (CheyTac 공식)
      mvSd: 4.0,
      sgFactor: 1.9,
      desc: '선반 가공한 구리-니켈 합금 솔리드 탄두(Balanced Flight Projectile)로 매우 안정적인 비행과 극히 높은 탄도계수를 얻어 2,500야드 이상의 교전을 가능하게 한다. CheyTac 공식 제원 기준 G1 탄도계수 0.949, 총구속도 2,752 fps, 총구에너지 8,372 ft-lb.',
      descSource: 'official',
      descSourceUrl: 'https://cheytac.com/product/cheytac-408-419-gr-ammunition/',
    },
  ],

  /* 임무: 사거리·기상·지형이 서로 다른 시나리오.
   * spotterErr: 관측수 제원의 오차 스케일(난이도) */
  missions: [
    {
      id: 'farm',
      name: '농장 훈련 — 300 m',
      briefing: '낡은 헛간 옆 사격 훈련장. 바람이 약하고 기상이 온화하다. 낙차 보정과 스코프 조작을 익혀라.',
      distanceM: 300,
      env: {
        tempC: 18, rhPct: 45, altitudeM: 60, pressurehPa: null,
        windSpeed: 1.5, windFromDeg: 250, fireAzimuthDeg: 0,
        latitudeDeg: 37.5, inclineDeg: 0, earthCurvature: false,
        gustiness: 0.15, lightLevel: 1.0,
      },
      target: { widthM: 0.45, heightM: 0.75, type: 'steel' },
      spotterErr: 0.0,
      terrain: 'farm',
    },
    {
      id: 'forest',
      name: '삼림 사대 — 600 m',
      briefing: '소나무 숲으로 둘러싸인 사격장. 표적 뒤 흙벽(백스톱)이 착탄을 보여준다. 간헐적 측풍에 주의.',
      distanceM: 600,
      env: {
        tempC: 14, rhPct: 60, altitudeM: 150, pressurehPa: null,
        windSpeed: 3.5, windFromDeg: 130, fireAzimuthDeg: 40,
        latitudeDeg: 37.2, inclineDeg: 0, earthCurvature: false,
        gustiness: 0.3, lightLevel: 1.0,
      },
      target: { widthM: 0.45, heightM: 0.75, type: 'steel' },
      spotterErr: 0.05,
      terrain: 'forest',
    },
    {
      id: 'grassland',
      name: '초원 횡풍 — 800 m',
      briefing: '탁 트인 초원, 강한 측풍이 분다. 풍향·풍속을 읽고 편류를 보정하라.',
      distanceM: 800,
      env: {
        tempC: 24, rhPct: 55, altitudeM: 300, pressurehPa: null,
        windSpeed: 6.5, windFromDeg: 95, fireAzimuthDeg: 10,
        latitudeDeg: 38.0, inclineDeg: 0, earthCurvature: false,
        gustiness: 0.35, lightLevel: 1.0,
      },
      target: { widthM: 0.45, heightM: 0.75, type: 'steel' },
      spotterErr: 0.1,
      terrain: 'plains',
    },
    {
      id: 'mountain',
      name: '산악 경사 사격 — 1,200 m',
      briefing: '고도 2,000 m 능선에서 아래쪽 계곡의 표적을 노린다. 공기가 희박해 낙차가 줄고, 경사 사격 보정이 필요하다.',
      distanceM: 1200,
      env: {
        tempC: 2, rhPct: 30, altitudeM: 2000, pressurehPa: null,
        windSpeed: 4.0, windFromDeg: 310, fireAzimuthDeg: 140,
        latitudeDeg: 38.5, inclineDeg: -12, earthCurvature: false,
        gustiness: 0.3, lightLevel: 0.95,
      },
      target: { widthM: 0.5, heightM: 0.8, type: 'steel' },
      spotterErr: 0.2,
      terrain: 'mountain',
    },
    {
      id: 'desert',
      name: '사막 돌풍 — 1,500 m',
      briefing: '고온 사막. 돌풍이 불규칙하고 아지랑이가 심하다. 바람이 잠잠해지는 순간을 노려라.',
      distanceM: 1500,
      env: {
        tempC: 41, rhPct: 10, altitudeM: 500, pressurehPa: null,
        windSpeed: 5.0, windFromDeg: 200, fireAzimuthDeg: 270,
        latitudeDeg: 30.0, inclineDeg: 0, earthCurvature: false,
        gustiness: 0.6, lightLevel: 1.1,
      },
      target: { widthM: 0.5, heightM: 0.8, type: 'steel' },
      spotterErr: 0.3,
      terrain: 'desert',
    },
    {
      id: 'extreme',
      name: '극한 초장거리 — 2,200 m',
      briefing: '초장거리 사격. 이 거리에선 코리올리 효과와 지구 곡률까지 탄도에 영향을 준다. 탄도 계산기를 신뢰하라.',
      distanceM: 2200,
      env: {
        tempC: 12, rhPct: 40, altitudeM: 900, pressurehPa: null,
        windSpeed: 3.0, windFromDeg: 180, fireAzimuthDeg: 90,
        latitudeDeg: 45.0, inclineDeg: 0, earthCurvature: true,
        gustiness: 0.25, lightLevel: 0.9,
      },
      target: { widthM: 1.0, heightM: 1.0, type: 'plate' },
      spotterErr: 0.35,
      terrain: 'tundra',
    },
  ],

  getRifle(id) { return this.rifles.find(r => r.id === id); },
  getAmmo(id) { return this.ammo.find(a => a.id === id); },
  getMission(id) { return this.missions.find(m => m.id === id); },
};
